version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=standardise
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379